name: Deploy to EC2

on:
  push:
    branches:
      - master  # Triggers on merge/push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the latest code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Node.js for building
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Match your EC2 Node.js version

      # Install Backend Dependencies and Verify
      - name: Install Backend Dependencies
        run: |
          cd server
          npm install

      # Install Frontend Dependencies and Build
      - name: Build Frontend
        run: |
          cd client
          npm install
          npm run build

      # Deploy to EC2 via SSH
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Navigate to project directory
            cd ~/cricket-app

            # Pull latest changes
            git pull origin main

            # Update Backend
            cd server
            npm install
            pm2 restart cricket-backend

            # Update Frontend
            cd ../client
            npm install
            npm run build
            sudo pm2 restart cricket-frontend